install:
  - curl -sSL -o ./hugo.tar.gz https://github.com/spf13/hugo/releases/download/v0.21/hugo_0.21_Linux-64bit.tar.gz
  - tar -xzf /tmp/hugo.tar.gz -C ./
  - rm ./hugo.tar.gz

script:
  - ./hugo

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_API_KEY
  on:
    branch: master
  local_dir: public
  repo: fanach.github.io
  target_branch: master

