sudo: false

language: go

cache:
  directories:
  - $GOPATH

install: go get -v github.com/spf13/hugo

script:
  - pwd
  - hugo

deploy:
  provider: pages
  skip_cleanup: true
  # token is set in travis-ci.org dashboard
  github_token: $GITHUB_API_KEY
  on:
    branch: master
  local_dir: public
  repo: fanach/fanach.github.io
  target_branch: master
  email: deploy@travis-ci.org
  name: deployment-bot
